package com.proint1.udea.actividad;

// default package
// Generated 8/11/2014 05:44:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbActReporteDcteGralTemp generated by hbm2java
 */
public class TbActReporteDcteGralTemp implements java.io.Serializable {

	private long nbKey;
	private String vrMcuDescripcion;
	private Long nbVpeIdn;
	private Short nbSemAgno;
	private Byte nbSemPeriodo;
	private String vrCurNombre;
	private String vrGpoNumero;
	private String vrTacNombre;
	private Date dtAdtfecha;
	private String vrPerNombres;
	private String vrPerApellidos;

	public TbActReporteDcteGralTemp() {
	}

	public TbActReporteDcteGralTemp(long nbKey) {
		this.nbKey = nbKey;
	}

	public TbActReporteDcteGralTemp(long nbKey, String vrMcuDescripcion,
			Long nbVpeIdn, Short nbSemAgno, Byte nbSemPeriodo,
			String vrCurNombre, String vrGpoNumero, String vrTacNombre,
			Date dtAdtfecha, String vrPerNombres, String vrPerApellidos) {
		this.nbKey = nbKey;
		this.vrMcuDescripcion = vrMcuDescripcion;
		this.nbVpeIdn = nbVpeIdn;
		this.nbSemAgno = nbSemAgno;
		this.nbSemPeriodo = nbSemPeriodo;
		this.vrCurNombre = vrCurNombre;
		this.vrGpoNumero = vrGpoNumero;
		this.vrTacNombre = vrTacNombre;
		this.dtAdtfecha = dtAdtfecha;
		this.vrPerNombres = vrPerNombres;
		this.vrPerApellidos = vrPerApellidos;
	}

	public long getNbKey() {
		return this.nbKey++;
	}

	public void setNbKey(long nbKey) {
		this.nbKey = nbKey;
	}

	public String getVrMcuDescripcion() {
		return this.vrMcuDescripcion;
	}

	public void setVrMcuDescripcion(String vrMcuDescripcion) {
		this.vrMcuDescripcion = vrMcuDescripcion;
	}

	public Long getNbVpeIdn() {
		return this.nbVpeIdn;
	}

	public void setNbVpeIdn(Long nbVpeIdn) {
		this.nbVpeIdn = nbVpeIdn;
	}

	public Short getNbSemAgno() {
		return this.nbSemAgno;
	}

	public void setNbSemAgno(Short nbSemAgno) {
		this.nbSemAgno = nbSemAgno;
	}

	public Byte getNbSemPeriodo() {
		return this.nbSemPeriodo;
	}

	public void setNbSemPeriodo(Byte nbSemPeriodo) {
		this.nbSemPeriodo = nbSemPeriodo;
	}

	public String getVrCurNombre() {
		return this.vrCurNombre;
	}

	public void setVrCurNombre(String vrCurNombre) {
		this.vrCurNombre = vrCurNombre;
	}

	public String getVrGpoNumero() {
		return this.vrGpoNumero;
	}

	public void setVrGpoNumero(String vrGpoNumero) {
		this.vrGpoNumero = vrGpoNumero;
	}

	public String getVrTacNombre() {
		return this.vrTacNombre;
	}

	public void setVrTacNombre(String vrTacNombre) {
		this.vrTacNombre = vrTacNombre;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public String getVrPerNombres() {
		return this.vrPerNombres;
	}

	public void setVrPerNombres(String vrPerNombres) {
		this.vrPerNombres = vrPerNombres;
	}

	public String getVrPerApellidos() {
		return this.vrPerApellidos;
	}

	public void setVrPerApellidos(String vrPerApellidos) {
		this.vrPerApellidos = vrPerApellidos;
	}

}
