package com.proint1.udea.actividad;

// default package
// Generated 24/11/2014 10:29:53 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.proint1.udea.administracion.TbAdmDocente;
import com.proint1.udea.administracion.TbAdmGrupo;

/**
 * TbActDocentexgrupo generated by hbm2java
 */
public class TbActDocentexgrupo implements java.io.Serializable {

	private long nbDogIdn;
	private TbAdmDocente tbAdmDocente;
	private TbAdmGrupo tbAdmGrupo;
	private BigDecimal nbDogTiempototal;
	private String vrAdtusuario;
	private Date dtAdtfecha;
	private Set tbActReporteactividads = new HashSet(0);

	public TbActDocentexgrupo() {
	}

	public TbActDocentexgrupo(long nbDogIdn, TbAdmDocente tbAdmDocente,
			TbAdmGrupo tbAdmGrupo) {
		this.nbDogIdn = nbDogIdn;
		this.tbAdmDocente = tbAdmDocente;
		this.tbAdmGrupo = tbAdmGrupo;
	}

	public TbActDocentexgrupo(long nbDogIdn, TbAdmDocente tbAdmDocente,
			TbAdmGrupo tbAdmGrupo, BigDecimal nbDogTiempototal,
			String vrAdtusuario, Date dtAdtfecha, Set tbActReporteactividads) {
		this.nbDogIdn = nbDogIdn;
		this.tbAdmDocente = tbAdmDocente;
		this.tbAdmGrupo = tbAdmGrupo;
		this.nbDogTiempototal = nbDogTiempototal;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
		this.tbActReporteactividads = tbActReporteactividads;
	}

	public long getNbDogIdn() {
		return this.nbDogIdn;
	}

	public void setNbDogIdn(long nbDogIdn) {
		this.nbDogIdn = nbDogIdn;
	}

	public TbAdmDocente getTbAdmDocente() {
		return this.tbAdmDocente;
	}

	public void setTbAdmDocente(TbAdmDocente tbAdmDocente) {
		this.tbAdmDocente = tbAdmDocente;
	}

	public TbAdmGrupo getTbAdmGrupo() {
		return this.tbAdmGrupo;
	}

	public void setTbAdmGrupo(TbAdmGrupo tbAdmGrupo) {
		this.tbAdmGrupo = tbAdmGrupo;
	}

	public BigDecimal getNbDogTiempototal() {
		return this.nbDogTiempototal;
	}

	public void setNbDogTiempototal(BigDecimal nbDogTiempototal) {
		this.nbDogTiempototal = nbDogTiempototal;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public Set getTbActReporteactividads() {
		return this.tbActReporteactividads;
	}

	public void setTbActReporteactividads(Set tbActReporteactividads) {
		this.tbActReporteactividads = tbActReporteactividads;
	}

}
