package com.proint1.udea.administracion;

// default package
// Generated 24/11/2014 10:29:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbAdmPermisosxrol generated by hbm2java
 */
public class TbAdmPermisosxrol implements java.io.Serializable {

	private TbAdmPermisosxrolId id;
	private TbAdmRecurso tbAdmRecurso;
	private TbAdmRol tbAdmRol;

	public TbAdmPermisosxrol() {
	}

	public TbAdmPermisosxrol(TbAdmPermisosxrolId id, TbAdmRecurso tbAdmRecurso,
			TbAdmRol tbAdmRol) {
		this.id = id;
		this.tbAdmRecurso = tbAdmRecurso;
		this.tbAdmRol = tbAdmRol;
	}

	public TbAdmPermisosxrolId getId() {
		return this.id;
	}

	public void setId(TbAdmPermisosxrolId id) {
		this.id = id;
	}

	public TbAdmRecurso getTbAdmRecurso() {
		return this.tbAdmRecurso;
	}

	public void setTbAdmRecurso(TbAdmRecurso tbAdmRecurso) {
		this.tbAdmRecurso = tbAdmRecurso;
	}

	public TbAdmRol getTbAdmRol() {
		return this.tbAdmRol;
	}

	public void setTbAdmRol(TbAdmRol tbAdmRol) {
		this.tbAdmRol = tbAdmRol;
	}

}
