package com.proint1.udea.administracion;

// default package
// Generated 24/11/2014 10:29:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmUnidadAcademica generated by hbm2java
 */
public class TbAdmUnidadAcademica implements java.io.Serializable {

	private long nbUniIdn;
	private String vrUniNombre;
	private String vrAdtusuario;
	private Date dtAdtfecha;
	private Set tbAdmDependenciaAcademicas = new HashSet(0);

	public TbAdmUnidadAcademica() {
	}

	public TbAdmUnidadAcademica(long nbUniIdn, String vrUniNombre) {
		this.nbUniIdn = nbUniIdn;
		this.vrUniNombre = vrUniNombre;
	}

	public TbAdmUnidadAcademica(long nbUniIdn, String vrUniNombre,
			String vrAdtusuario, Date dtAdtfecha, Set tbAdmDependenciaAcademicas) {
		this.nbUniIdn = nbUniIdn;
		this.vrUniNombre = vrUniNombre;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
		this.tbAdmDependenciaAcademicas = tbAdmDependenciaAcademicas;
	}

	public long getNbUniIdn() {
		return this.nbUniIdn;
	}

	public void setNbUniIdn(long nbUniIdn) {
		this.nbUniIdn = nbUniIdn;
	}

	public String getVrUniNombre() {
		return this.vrUniNombre;
	}

	public void setVrUniNombre(String vrUniNombre) {
		this.vrUniNombre = vrUniNombre;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public Set getTbAdmDependenciaAcademicas() {
		return this.tbAdmDependenciaAcademicas;
	}

	public void setTbAdmDependenciaAcademicas(Set tbAdmDependenciaAcademicas) {
		this.tbAdmDependenciaAcademicas = tbAdmDependenciaAcademicas;
	}

}
