package com.proint1.udea.administracion;

// default package
// Generated 24/11/2014 10:29:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmEstudiante generated by hbm2java
 */
public class TbAdmEstudiante implements java.io.Serializable {

	private long nbEstIdn;
	private TbAdmPersona tbAdmPersona;
	private String vrCodigointernno;
	private Set tbAdmMatriculas = new HashSet(0);

	public TbAdmEstudiante() {
	}

	public TbAdmEstudiante(long nbEstIdn, TbAdmPersona tbAdmPersona) {
		this.nbEstIdn = nbEstIdn;
		this.tbAdmPersona = tbAdmPersona;
	}

	public TbAdmEstudiante(long nbEstIdn, TbAdmPersona tbAdmPersona,
			String vrCodigointernno, Set tbAdmMatriculas) {
		this.nbEstIdn = nbEstIdn;
		this.tbAdmPersona = tbAdmPersona;
		this.vrCodigointernno = vrCodigointernno;
		this.tbAdmMatriculas = tbAdmMatriculas;
	}

	public long getNbEstIdn() {
		return this.nbEstIdn;
	}

	public void setNbEstIdn(long nbEstIdn) {
		this.nbEstIdn = nbEstIdn;
	}

	public TbAdmPersona getTbAdmPersona() {
		return this.tbAdmPersona;
	}

	public void setTbAdmPersona(TbAdmPersona tbAdmPersona) {
		this.tbAdmPersona = tbAdmPersona;
	}

	public String getVrCodigointernno() {
		return this.vrCodigointernno;
	}

	public void setVrCodigointernno(String vrCodigointernno) {
		this.vrCodigointernno = vrCodigointernno;
	}

	public Set getTbAdmMatriculas() {
		return this.tbAdmMatriculas;
	}

	public void setTbAdmMatriculas(Set tbAdmMatriculas) {
		this.tbAdmMatriculas = tbAdmMatriculas;
	}

}
