package com.proint1.udea.administracion;

// default package
// Generated 24/11/2014 10:29:53 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TbAdmTareasProgramadas generated by hbm2java
 */
public class TbAdmTareasProgramadas implements java.io.Serializable {

	private BigDecimal nbTprIdn;
	private TbAdmDependenciaAcademica tbAdmDependenciaAcademica;
	private String vrTprNombre;
	private String vrTprManager;
	private char nbTprActiva;
	private String vrAdtusuario;
	private Date dtAdtfecha;

	public TbAdmTareasProgramadas() {
	}

	public TbAdmTareasProgramadas(BigDecimal nbTprIdn,
			TbAdmDependenciaAcademica tbAdmDependenciaAcademica,
			String vrTprNombre, String vrTprManager, char nbTprActiva) {
		this.nbTprIdn = nbTprIdn;
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
		this.vrTprNombre = vrTprNombre;
		this.vrTprManager = vrTprManager;
		this.nbTprActiva = nbTprActiva;
	}

	public TbAdmTareasProgramadas(BigDecimal nbTprIdn,
			TbAdmDependenciaAcademica tbAdmDependenciaAcademica,
			String vrTprNombre, String vrTprManager, char nbTprActiva,
			String vrAdtusuario, Date dtAdtfecha) {
		this.nbTprIdn = nbTprIdn;
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
		this.vrTprNombre = vrTprNombre;
		this.vrTprManager = vrTprManager;
		this.nbTprActiva = nbTprActiva;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
	}

	public BigDecimal getNbTprIdn() {
		return this.nbTprIdn;
	}

	public void setNbTprIdn(BigDecimal nbTprIdn) {
		this.nbTprIdn = nbTprIdn;
	}

	public TbAdmDependenciaAcademica getTbAdmDependenciaAcademica() {
		return this.tbAdmDependenciaAcademica;
	}

	public void setTbAdmDependenciaAcademica(
			TbAdmDependenciaAcademica tbAdmDependenciaAcademica) {
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
	}

	public String getVrTprNombre() {
		return this.vrTprNombre;
	}

	public void setVrTprNombre(String vrTprNombre) {
		this.vrTprNombre = vrTprNombre;
	}

	public String getVrTprManager() {
		return this.vrTprManager;
	}

	public void setVrTprManager(String vrTprManager) {
		this.vrTprManager = vrTprManager;
	}

	public char getNbTprActiva() {
		return this.nbTprActiva;
	}

	public void setNbTprActiva(char nbTprActiva) {
		this.nbTprActiva = nbTprActiva;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

}
