package com.proint1.udea.actividad;

// default package
// Generated 24/11/2014 10:29:53 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TbActReporteactividad generated by hbm2java
 */
public class TbActReporteactividad implements java.io.Serializable {

	private long nbRacIdn;
	private TbActDocentexgrupo tbActDocentexgrupo;
	private TbActTipoActividad tbActTipoActividad;
	private Date dtRacFecha;
	private String vrRacDescripcion;
	private BigDecimal nbRacTiempo;
	private String vrAdtusuario;
	private Date dtAdtfecha;

	public TbActReporteactividad() {
	}

	public TbActReporteactividad(long nbRacIdn,
			TbActDocentexgrupo tbActDocentexgrupo,
			TbActTipoActividad tbActTipoActividad, Date dtRacFecha,
			BigDecimal nbRacTiempo) {
		this.nbRacIdn = nbRacIdn;
		this.tbActDocentexgrupo = tbActDocentexgrupo;
		this.tbActTipoActividad = tbActTipoActividad;
		this.dtRacFecha = dtRacFecha;
		this.nbRacTiempo = nbRacTiempo;
	}

	public TbActReporteactividad(long nbRacIdn,
			TbActDocentexgrupo tbActDocentexgrupo,
			TbActTipoActividad tbActTipoActividad, Date dtRacFecha,
			String vrRacDescripcion, BigDecimal nbRacTiempo,
			String vrAdtusuario, Date dtAdtfecha) {
		this.nbRacIdn = nbRacIdn;
		this.tbActDocentexgrupo = tbActDocentexgrupo;
		this.tbActTipoActividad = tbActTipoActividad;
		this.dtRacFecha = dtRacFecha;
		this.vrRacDescripcion = vrRacDescripcion;
		this.nbRacTiempo = nbRacTiempo;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
	}

	public long getNbRacIdn() {
		return this.nbRacIdn;
	}

	public void setNbRacIdn(long nbRacIdn) {
		this.nbRacIdn = nbRacIdn;
	}

	public TbActDocentexgrupo getTbActDocentexgrupo() {
		return this.tbActDocentexgrupo;
	}

	public void setTbActDocentexgrupo(TbActDocentexgrupo tbActDocentexgrupo) {
		this.tbActDocentexgrupo = tbActDocentexgrupo;
	}

	public TbActTipoActividad getTbActTipoActividad() {
		return this.tbActTipoActividad;
	}

	public void setTbActTipoActividad(TbActTipoActividad tbActTipoActividad) {
		this.tbActTipoActividad = tbActTipoActividad;
	}

	public Date getDtRacFecha() {
		return this.dtRacFecha;
	}

	public void setDtRacFecha(Date dtRacFecha) {
		this.dtRacFecha = dtRacFecha;
	}

	public String getVrRacDescripcion() {
		return this.vrRacDescripcion;
	}

	public void setVrRacDescripcion(String vrRacDescripcion) {
		this.vrRacDescripcion = vrRacDescripcion;
	}

	public BigDecimal getNbRacTiempo() {
		return this.nbRacTiempo;
	}

	public void setNbRacTiempo(BigDecimal nbRacTiempo) {
		this.nbRacTiempo = nbRacTiempo;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

}
