package com.proint1.udea.administracion;

// default package
// Generated 24/11/2014 10:29:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbAdmUsuarioxrol generated by hbm2java
 */
public class TbAdmUsuarioxrol implements java.io.Serializable {

	private long nbUxrIdn;
	private TbAdmRol tbAdmRol;
	private TbAdmUsuario tbAdmUsuario;

	public TbAdmUsuarioxrol() {
	}

	public TbAdmUsuarioxrol(long nbUxrIdn, TbAdmRol tbAdmRol,
			TbAdmUsuario tbAdmUsuario) {
		this.nbUxrIdn = nbUxrIdn;
		this.tbAdmRol = tbAdmRol;
		this.tbAdmUsuario = tbAdmUsuario;
	}

	public long getNbUxrIdn() {
		return this.nbUxrIdn;
	}

	public void setNbUxrIdn(long nbUxrIdn) {
		this.nbUxrIdn = nbUxrIdn;
	}

	public TbAdmRol getTbAdmRol() {
		return this.tbAdmRol;
	}

	public void setTbAdmRol(TbAdmRol tbAdmRol) {
		this.tbAdmRol = tbAdmRol;
	}

	public TbAdmUsuario getTbAdmUsuario() {
		return this.tbAdmUsuario;
	}

	public void setTbAdmUsuario(TbAdmUsuario tbAdmUsuario) {
		this.tbAdmUsuario = tbAdmUsuario;
	}

}
