package com.proint1.udea.administracion;

// default package
// Generated 24/11/2014 10:29:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmSemestrexcurso generated by hbm2java
 */
public class TbAdmSemestrexcurso implements java.io.Serializable {

	private long nbScuIdn;
	private TbAdmSemestre tbAdmSemestre;
	private TbAdmGrupo tbAdmGrupo;
	private TbAdmCurso tbAdmCurso;
	private TbAdmModalidadCurso tbAdmModalidadCurso;
	private Set tbMicMicrocurriculos = new HashSet(0);

	public TbAdmSemestrexcurso() {
	}

	public TbAdmSemestrexcurso(long nbScuIdn, TbAdmSemestre tbAdmSemestre,
			TbAdmGrupo tbAdmGrupo, TbAdmCurso tbAdmCurso,
			TbAdmModalidadCurso tbAdmModalidadCurso) {
		this.nbScuIdn = nbScuIdn;
		this.tbAdmSemestre = tbAdmSemestre;
		this.tbAdmGrupo = tbAdmGrupo;
		this.tbAdmCurso = tbAdmCurso;
		this.tbAdmModalidadCurso = tbAdmModalidadCurso;
	}

	public TbAdmSemestrexcurso(long nbScuIdn, TbAdmSemestre tbAdmSemestre,
			TbAdmGrupo tbAdmGrupo, TbAdmCurso tbAdmCurso,
			TbAdmModalidadCurso tbAdmModalidadCurso, Set tbMicMicrocurriculos) {
		this.nbScuIdn = nbScuIdn;
		this.tbAdmSemestre = tbAdmSemestre;
		this.tbAdmGrupo = tbAdmGrupo;
		this.tbAdmCurso = tbAdmCurso;
		this.tbAdmModalidadCurso = tbAdmModalidadCurso;
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
	}

	public long getNbScuIdn() {
		return this.nbScuIdn;
	}

	public void setNbScuIdn(long nbScuIdn) {
		this.nbScuIdn = nbScuIdn;
	}

	public TbAdmSemestre getTbAdmSemestre() {
		return this.tbAdmSemestre;
	}

	public void setTbAdmSemestre(TbAdmSemestre tbAdmSemestre) {
		this.tbAdmSemestre = tbAdmSemestre;
	}

	public TbAdmGrupo getTbAdmGrupo() {
		return this.tbAdmGrupo;
	}

	public void setTbAdmGrupo(TbAdmGrupo tbAdmGrupo) {
		this.tbAdmGrupo = tbAdmGrupo;
	}

	public TbAdmCurso getTbAdmCurso() {
		return this.tbAdmCurso;
	}

	public void setTbAdmCurso(TbAdmCurso tbAdmCurso) {
		this.tbAdmCurso = tbAdmCurso;
	}

	public TbAdmModalidadCurso getTbAdmModalidadCurso() {
		return this.tbAdmModalidadCurso;
	}

	public void setTbAdmModalidadCurso(TbAdmModalidadCurso tbAdmModalidadCurso) {
		this.tbAdmModalidadCurso = tbAdmModalidadCurso;
	}

	public Set getTbMicMicrocurriculos() {
		return this.tbMicMicrocurriculos;
	}

	public void setTbMicMicrocurriculos(Set tbMicMicrocurriculos) {
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
	}

}
