package com.proint1.udea.administracion;

// default package
// Generated 24/11/2014 10:29:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmDocente generated by hbm2java
 */
public class TbAdmDocente implements java.io.Serializable {

	private long nbDocIdn;
	private TbAdmPersona tbAdmPersona;
	private String vrDocIdentificacion;
	private String vrDocNombres;
	private String vrDocCelular;
	private String vrDocEmail;
	private String vrAdtusuario;
	private Date dtAdtfecha;
	private Set tbActDocentexgrupos = new HashSet(0);
	private Set tbAdmDocentesxdependencias = new HashSet(0);

	public TbAdmDocente() {
	}

	public TbAdmDocente(long nbDocIdn, TbAdmPersona tbAdmPersona,
			String vrDocIdentificacion, String vrDocNombres) {
		this.nbDocIdn = nbDocIdn;
		this.tbAdmPersona = tbAdmPersona;
		this.vrDocIdentificacion = vrDocIdentificacion;
		this.vrDocNombres = vrDocNombres;
	}

	public TbAdmDocente(long nbDocIdn, TbAdmPersona tbAdmPersona,
			String vrDocIdentificacion, String vrDocNombres,
			String vrDocCelular, String vrDocEmail, String vrAdtusuario,
			Date dtAdtfecha, Set tbActDocentexgrupos,
			Set tbAdmDocentesxdependencias) {
		this.nbDocIdn = nbDocIdn;
		this.tbAdmPersona = tbAdmPersona;
		this.vrDocIdentificacion = vrDocIdentificacion;
		this.vrDocNombres = vrDocNombres;
		this.vrDocCelular = vrDocCelular;
		this.vrDocEmail = vrDocEmail;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
		this.tbActDocentexgrupos = tbActDocentexgrupos;
		this.tbAdmDocentesxdependencias = tbAdmDocentesxdependencias;
	}

	public long getNbDocIdn() {
		return this.nbDocIdn;
	}

	public void setNbDocIdn(long nbDocIdn) {
		this.nbDocIdn = nbDocIdn;
	}

	public TbAdmPersona getTbAdmPersona() {
		return this.tbAdmPersona;
	}

	public void setTbAdmPersona(TbAdmPersona tbAdmPersona) {
		this.tbAdmPersona = tbAdmPersona;
	}

	public String getVrDocIdentificacion() {
		return this.vrDocIdentificacion;
	}

	public void setVrDocIdentificacion(String vrDocIdentificacion) {
		this.vrDocIdentificacion = vrDocIdentificacion;
	}

	public String getVrDocNombres() {
		return this.vrDocNombres;
	}

	public void setVrDocNombres(String vrDocNombres) {
		this.vrDocNombres = vrDocNombres;
	}

	public String getVrDocCelular() {
		return this.vrDocCelular;
	}

	public void setVrDocCelular(String vrDocCelular) {
		this.vrDocCelular = vrDocCelular;
	}

	public String getVrDocEmail() {
		return this.vrDocEmail;
	}

	public void setVrDocEmail(String vrDocEmail) {
		this.vrDocEmail = vrDocEmail;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public Set getTbActDocentexgrupos() {
		return this.tbActDocentexgrupos;
	}

	public void setTbActDocentexgrupos(Set tbActDocentexgrupos) {
		this.tbActDocentexgrupos = tbActDocentexgrupos;
	}

	public Set getTbAdmDocentesxdependencias() {
		return this.tbAdmDocentesxdependencias;
	}

	public void setTbAdmDocentesxdependencias(Set tbAdmDocentesxdependencias) {
		this.tbAdmDocentesxdependencias = tbAdmDocentesxdependencias;
	}

}
