package com.proint1.udea.administracion;

// default package
// Generated 24/11/2014 10:29:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmDependenciaAcademica generated by hbm2java
 */
public class TbAdmDependenciaAcademica implements java.io.Serializable {

	private long nbDepIdn;
	private TbAdmTipoDependencia tbAdmTipoDependencia;
	private TbAdmUnidadAcademica tbAdmUnidadAcademica;
	private TbAdmDependenciaAcademica tbAdmDependenciaAcademica;
	private String vrDepNombre;
	private Set tbAdmDocentesxdependencias = new HashSet(0);
	private Set tbAdmPropiedadeses = new HashSet(0);
	private Set tbAdmDependenciaAcademicas = new HashSet(0);
	private Set tbAdmTareasProgramadases = new HashSet(0);
	private Set tbAdmCursos = new HashSet(0);
	private Set tbAdmMatriculas = new HashSet(0);
	private Set tbAdmSemestres = new HashSet(0);

	public TbAdmDependenciaAcademica() {
	}

	public TbAdmDependenciaAcademica(long nbDepIdn,
			TbAdmTipoDependencia tbAdmTipoDependencia,
			TbAdmUnidadAcademica tbAdmUnidadAcademica, String vrDepNombre) {
		this.nbDepIdn = nbDepIdn;
		this.tbAdmTipoDependencia = tbAdmTipoDependencia;
		this.tbAdmUnidadAcademica = tbAdmUnidadAcademica;
		this.vrDepNombre = vrDepNombre;
	}

	public TbAdmDependenciaAcademica(long nbDepIdn,
			TbAdmTipoDependencia tbAdmTipoDependencia,
			TbAdmUnidadAcademica tbAdmUnidadAcademica,
			TbAdmDependenciaAcademica tbAdmDependenciaAcademica,
			String vrDepNombre, Set tbAdmDocentesxdependencias,
			Set tbAdmPropiedadeses, Set tbAdmDependenciaAcademicas,
			Set tbAdmTareasProgramadases, Set tbAdmCursos, Set tbAdmMatriculas,
			Set tbAdmSemestres) {
		this.nbDepIdn = nbDepIdn;
		this.tbAdmTipoDependencia = tbAdmTipoDependencia;
		this.tbAdmUnidadAcademica = tbAdmUnidadAcademica;
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
		this.vrDepNombre = vrDepNombre;
		this.tbAdmDocentesxdependencias = tbAdmDocentesxdependencias;
		this.tbAdmPropiedadeses = tbAdmPropiedadeses;
		this.tbAdmDependenciaAcademicas = tbAdmDependenciaAcademicas;
		this.tbAdmTareasProgramadases = tbAdmTareasProgramadases;
		this.tbAdmCursos = tbAdmCursos;
		this.tbAdmMatriculas = tbAdmMatriculas;
		this.tbAdmSemestres = tbAdmSemestres;
	}

	public long getNbDepIdn() {
		return this.nbDepIdn;
	}

	public void setNbDepIdn(long nbDepIdn) {
		this.nbDepIdn = nbDepIdn;
	}

	public TbAdmTipoDependencia getTbAdmTipoDependencia() {
		return this.tbAdmTipoDependencia;
	}

	public void setTbAdmTipoDependencia(
			TbAdmTipoDependencia tbAdmTipoDependencia) {
		this.tbAdmTipoDependencia = tbAdmTipoDependencia;
	}

	public TbAdmUnidadAcademica getTbAdmUnidadAcademica() {
		return this.tbAdmUnidadAcademica;
	}

	public void setTbAdmUnidadAcademica(
			TbAdmUnidadAcademica tbAdmUnidadAcademica) {
		this.tbAdmUnidadAcademica = tbAdmUnidadAcademica;
	}

	public TbAdmDependenciaAcademica getTbAdmDependenciaAcademica() {
		return this.tbAdmDependenciaAcademica;
	}

	public void setTbAdmDependenciaAcademica(
			TbAdmDependenciaAcademica tbAdmDependenciaAcademica) {
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
	}

	public String getVrDepNombre() {
		return this.vrDepNombre;
	}

	public void setVrDepNombre(String vrDepNombre) {
		this.vrDepNombre = vrDepNombre;
	}

	public Set getTbAdmDocentesxdependencias() {
		return this.tbAdmDocentesxdependencias;
	}

	public void setTbAdmDocentesxdependencias(Set tbAdmDocentesxdependencias) {
		this.tbAdmDocentesxdependencias = tbAdmDocentesxdependencias;
	}

	public Set getTbAdmPropiedadeses() {
		return this.tbAdmPropiedadeses;
	}

	public void setTbAdmPropiedadeses(Set tbAdmPropiedadeses) {
		this.tbAdmPropiedadeses = tbAdmPropiedadeses;
	}

	public Set getTbAdmDependenciaAcademicas() {
		return this.tbAdmDependenciaAcademicas;
	}

	public void setTbAdmDependenciaAcademicas(Set tbAdmDependenciaAcademicas) {
		this.tbAdmDependenciaAcademicas = tbAdmDependenciaAcademicas;
	}

	public Set getTbAdmTareasProgramadases() {
		return this.tbAdmTareasProgramadases;
	}

	public void setTbAdmTareasProgramadases(Set tbAdmTareasProgramadases) {
		this.tbAdmTareasProgramadases = tbAdmTareasProgramadases;
	}

	public Set getTbAdmCursos() {
		return this.tbAdmCursos;
	}

	public void setTbAdmCursos(Set tbAdmCursos) {
		this.tbAdmCursos = tbAdmCursos;
	}

	public Set getTbAdmMatriculas() {
		return this.tbAdmMatriculas;
	}

	public void setTbAdmMatriculas(Set tbAdmMatriculas) {
		this.tbAdmMatriculas = tbAdmMatriculas;
	}

	public Set getTbAdmSemestres() {
		return this.tbAdmSemestres;
	}

	public void setTbAdmSemestres(Set tbAdmSemestres) {
		this.tbAdmSemestres = tbAdmSemestres;
	}

}
