package com.proint1.udea.administracion;

// default package
// Generated 24/11/2014 10:29:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmSemestre generated by hbm2java
 */
public class TbAdmSemestre implements java.io.Serializable {

	private long nbSemIdn;
	private TbAdmEstadoSemestre tbAdmEstadoSemestre;
	private TbAdmDependenciaAcademica tbAdmDependenciaAcademica;
	private Short nbSemAgno;
	private Boolean nbSemPeriodo;
	private Date dtAdtfecha;
	private String vrAdtusuario;
	private Set tbAdmMatriculas = new HashSet(0);
	private Set tbAdmSemestrexcursos = new HashSet(0);

	public TbAdmSemestre() {
	}

	public TbAdmSemestre(long nbSemIdn,
			TbAdmEstadoSemestre tbAdmEstadoSemestre,
			TbAdmDependenciaAcademica tbAdmDependenciaAcademica) {
		this.nbSemIdn = nbSemIdn;
		this.tbAdmEstadoSemestre = tbAdmEstadoSemestre;
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
	}

	public TbAdmSemestre(long nbSemIdn,
			TbAdmEstadoSemestre tbAdmEstadoSemestre,
			TbAdmDependenciaAcademica tbAdmDependenciaAcademica,
			Short nbSemAgno, Boolean nbSemPeriodo, Date dtAdtfecha,
			String vrAdtusuario, Set tbAdmMatriculas, Set tbAdmSemestrexcursos) {
		this.nbSemIdn = nbSemIdn;
		this.tbAdmEstadoSemestre = tbAdmEstadoSemestre;
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
		this.nbSemAgno = nbSemAgno;
		this.nbSemPeriodo = nbSemPeriodo;
		this.dtAdtfecha = dtAdtfecha;
		this.vrAdtusuario = vrAdtusuario;
		this.tbAdmMatriculas = tbAdmMatriculas;
		this.tbAdmSemestrexcursos = tbAdmSemestrexcursos;
	}

	public long getNbSemIdn() {
		return this.nbSemIdn;
	}

	public void setNbSemIdn(long nbSemIdn) {
		this.nbSemIdn = nbSemIdn;
	}

	public TbAdmEstadoSemestre getTbAdmEstadoSemestre() {
		return this.tbAdmEstadoSemestre;
	}

	public void setTbAdmEstadoSemestre(TbAdmEstadoSemestre tbAdmEstadoSemestre) {
		this.tbAdmEstadoSemestre = tbAdmEstadoSemestre;
	}

	public TbAdmDependenciaAcademica getTbAdmDependenciaAcademica() {
		return this.tbAdmDependenciaAcademica;
	}

	public void setTbAdmDependenciaAcademica(
			TbAdmDependenciaAcademica tbAdmDependenciaAcademica) {
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
	}

	public Short getNbSemAgno() {
		return this.nbSemAgno;
	}

	public void setNbSemAgno(Short nbSemAgno) {
		this.nbSemAgno = nbSemAgno;
	}

	public Boolean getNbSemPeriodo() {
		return this.nbSemPeriodo;
	}

	public void setNbSemPeriodo(Boolean nbSemPeriodo) {
		this.nbSemPeriodo = nbSemPeriodo;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Set getTbAdmMatriculas() {
		return this.tbAdmMatriculas;
	}

	public void setTbAdmMatriculas(Set tbAdmMatriculas) {
		this.tbAdmMatriculas = tbAdmMatriculas;
	}

	public Set getTbAdmSemestrexcursos() {
		return this.tbAdmSemestrexcursos;
	}

	public void setTbAdmSemestrexcursos(Set tbAdmSemestrexcursos) {
		this.tbAdmSemestrexcursos = tbAdmSemestrexcursos;
	}

}
