package com.proint1.udea.administracion;

// default package
// Generated 24/11/2014 10:29:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbAdmMatricula generated by hbm2java
 */
public class TbAdmMatricula implements java.io.Serializable {

	private long nbMatIdn;
	private TbAdmSemestre tbAdmSemestre;
	private TbAdmGrupo tbAdmGrupo;
	private TbAdmEstudiante tbAdmEstudiante;
	private TbAdmDependenciaAcademica tbAdmDependenciaAcademica;

	public TbAdmMatricula() {
	}

	public TbAdmMatricula(long nbMatIdn, TbAdmSemestre tbAdmSemestre,
			TbAdmGrupo tbAdmGrupo, TbAdmEstudiante tbAdmEstudiante,
			TbAdmDependenciaAcademica tbAdmDependenciaAcademica) {
		this.nbMatIdn = nbMatIdn;
		this.tbAdmSemestre = tbAdmSemestre;
		this.tbAdmGrupo = tbAdmGrupo;
		this.tbAdmEstudiante = tbAdmEstudiante;
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
	}

	public long getNbMatIdn() {
		return this.nbMatIdn;
	}

	public void setNbMatIdn(long nbMatIdn) {
		this.nbMatIdn = nbMatIdn;
	}

	public TbAdmSemestre getTbAdmSemestre() {
		return this.tbAdmSemestre;
	}

	public void setTbAdmSemestre(TbAdmSemestre tbAdmSemestre) {
		this.tbAdmSemestre = tbAdmSemestre;
	}

	public TbAdmGrupo getTbAdmGrupo() {
		return this.tbAdmGrupo;
	}

	public void setTbAdmGrupo(TbAdmGrupo tbAdmGrupo) {
		this.tbAdmGrupo = tbAdmGrupo;
	}

	public TbAdmEstudiante getTbAdmEstudiante() {
		return this.tbAdmEstudiante;
	}

	public void setTbAdmEstudiante(TbAdmEstudiante tbAdmEstudiante) {
		this.tbAdmEstudiante = tbAdmEstudiante;
	}

	public TbAdmDependenciaAcademica getTbAdmDependenciaAcademica() {
		return this.tbAdmDependenciaAcademica;
	}

	public void setTbAdmDependenciaAcademica(
			TbAdmDependenciaAcademica tbAdmDependenciaAcademica) {
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
	}

}
