package com.proint1.udea.administracion;

// default package
// Generated 24/11/2014 10:29:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmPersona generated by hbm2java
 */
public class TbAdmPersona implements java.io.Serializable {

	private long nbPerIdn;
	private TbAdmTipoidentificacion tbAdmTipoidentificacion;
	private String vrPerAdtusuario;
	private Date dtPerAdtfecha;
	private String vrPerNombres;
	private String vrPerApellidos;
	private String vrPerIdentificacion;
	private String vrPerDireccion;
	private String vrPerTelefono;
	private String vrPerEmail;
	private Set tbAdmDocentes = new HashSet(0);
	private Set tbPrdAutors = new HashSet(0);
	private Set tbPrdGrupoinvestigacions = new HashSet(0);
	private Set tbAdmEstudiantes = new HashSet(0);
	private Set tbPrdMiembrosxgrupos = new HashSet(0);
	private Set tbAdmUsuarios = new HashSet(0);

	public TbAdmPersona() {
	}

	public TbAdmPersona(long nbPerIdn,
			TbAdmTipoidentificacion tbAdmTipoidentificacion,
			String vrPerAdtusuario, Date dtPerAdtfecha, String vrPerNombres,
			String vrPerApellidos, String vrPerIdentificacion) {
		this.nbPerIdn = nbPerIdn;
		this.tbAdmTipoidentificacion = tbAdmTipoidentificacion;
		this.vrPerAdtusuario = vrPerAdtusuario;
		this.dtPerAdtfecha = dtPerAdtfecha;
		this.vrPerNombres = vrPerNombres;
		this.vrPerApellidos = vrPerApellidos;
		this.vrPerIdentificacion = vrPerIdentificacion;
	}

	public TbAdmPersona(long nbPerIdn,
			TbAdmTipoidentificacion tbAdmTipoidentificacion,
			String vrPerAdtusuario, Date dtPerAdtfecha, String vrPerNombres,
			String vrPerApellidos, String vrPerIdentificacion,
			String vrPerDireccion, String vrPerTelefono, String vrPerEmail,
			Set tbAdmDocentes, Set tbPrdAutors, Set tbPrdGrupoinvestigacions,
			Set tbAdmEstudiantes, Set tbPrdMiembrosxgrupos, Set tbAdmUsuarios) {
		this.nbPerIdn = nbPerIdn;
		this.tbAdmTipoidentificacion = tbAdmTipoidentificacion;
		this.vrPerAdtusuario = vrPerAdtusuario;
		this.dtPerAdtfecha = dtPerAdtfecha;
		this.vrPerNombres = vrPerNombres;
		this.vrPerApellidos = vrPerApellidos;
		this.vrPerIdentificacion = vrPerIdentificacion;
		this.vrPerDireccion = vrPerDireccion;
		this.vrPerTelefono = vrPerTelefono;
		this.vrPerEmail = vrPerEmail;
		this.tbAdmDocentes = tbAdmDocentes;
		this.tbPrdAutors = tbPrdAutors;
		this.tbPrdGrupoinvestigacions = tbPrdGrupoinvestigacions;
		this.tbAdmEstudiantes = tbAdmEstudiantes;
		this.tbPrdMiembrosxgrupos = tbPrdMiembrosxgrupos;
		this.tbAdmUsuarios = tbAdmUsuarios;
	}

	public long getNbPerIdn() {
		return this.nbPerIdn;
	}

	public void setNbPerIdn(long nbPerIdn) {
		this.nbPerIdn = nbPerIdn;
	}

	public TbAdmTipoidentificacion getTbAdmTipoidentificacion() {
		return this.tbAdmTipoidentificacion;
	}

	public void setTbAdmTipoidentificacion(
			TbAdmTipoidentificacion tbAdmTipoidentificacion) {
		this.tbAdmTipoidentificacion = tbAdmTipoidentificacion;
	}

	public String getVrPerAdtusuario() {
		return this.vrPerAdtusuario;
	}

	public void setVrPerAdtusuario(String vrPerAdtusuario) {
		this.vrPerAdtusuario = vrPerAdtusuario;
	}

	public Date getDtPerAdtfecha() {
		return this.dtPerAdtfecha;
	}

	public void setDtPerAdtfecha(Date dtPerAdtfecha) {
		this.dtPerAdtfecha = dtPerAdtfecha;
	}

	public String getVrPerNombres() {
		return this.vrPerNombres;
	}

	public void setVrPerNombres(String vrPerNombres) {
		this.vrPerNombres = vrPerNombres;
	}

	public String getVrPerApellidos() {
		return this.vrPerApellidos;
	}

	public void setVrPerApellidos(String vrPerApellidos) {
		this.vrPerApellidos = vrPerApellidos;
	}

	public String getVrPerIdentificacion() {
		return this.vrPerIdentificacion;
	}

	public void setVrPerIdentificacion(String vrPerIdentificacion) {
		this.vrPerIdentificacion = vrPerIdentificacion;
	}

	public String getVrPerDireccion() {
		return this.vrPerDireccion;
	}

	public void setVrPerDireccion(String vrPerDireccion) {
		this.vrPerDireccion = vrPerDireccion;
	}

	public String getVrPerTelefono() {
		return this.vrPerTelefono;
	}

	public void setVrPerTelefono(String vrPerTelefono) {
		this.vrPerTelefono = vrPerTelefono;
	}

	public String getVrPerEmail() {
		return this.vrPerEmail;
	}

	public void setVrPerEmail(String vrPerEmail) {
		this.vrPerEmail = vrPerEmail;
	}

	public Set getTbAdmDocentes() {
		return this.tbAdmDocentes;
	}

	public void setTbAdmDocentes(Set tbAdmDocentes) {
		this.tbAdmDocentes = tbAdmDocentes;
	}

	public Set getTbPrdAutors() {
		return this.tbPrdAutors;
	}

	public void setTbPrdAutors(Set tbPrdAutors) {
		this.tbPrdAutors = tbPrdAutors;
	}

	public Set getTbPrdGrupoinvestigacions() {
		return this.tbPrdGrupoinvestigacions;
	}

	public void setTbPrdGrupoinvestigacions(Set tbPrdGrupoinvestigacions) {
		this.tbPrdGrupoinvestigacions = tbPrdGrupoinvestigacions;
	}

	public Set getTbAdmEstudiantes() {
		return this.tbAdmEstudiantes;
	}

	public void setTbAdmEstudiantes(Set tbAdmEstudiantes) {
		this.tbAdmEstudiantes = tbAdmEstudiantes;
	}

	public Set getTbPrdMiembrosxgrupos() {
		return this.tbPrdMiembrosxgrupos;
	}

	public void setTbPrdMiembrosxgrupos(Set tbPrdMiembrosxgrupos) {
		this.tbPrdMiembrosxgrupos = tbPrdMiembrosxgrupos;
	}

	public Set getTbAdmUsuarios() {
		return this.tbAdmUsuarios;
	}

	public void setTbAdmUsuarios(Set tbAdmUsuarios) {
		this.tbAdmUsuarios = tbAdmUsuarios;
	}

}
