package com.proint1.udea.administracion;

// default package
// Generated 24/11/2014 10:29:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmModalidadCurso generated by hbm2java
 */
public class TbAdmModalidadCurso implements java.io.Serializable {

	private long bnMcuIdn;
	private String vrMcuCodigo;
	private String vrMcuDescripcion;
	private Set tbAdmSemestrexcursos = new HashSet(0);

	public TbAdmModalidadCurso() {
	}

	public TbAdmModalidadCurso(long bnMcuIdn, String vrMcuCodigo,
			String vrMcuDescripcion) {
		this.bnMcuIdn = bnMcuIdn;
		this.vrMcuCodigo = vrMcuCodigo;
		this.vrMcuDescripcion = vrMcuDescripcion;
	}

	public TbAdmModalidadCurso(long bnMcuIdn, String vrMcuCodigo,
			String vrMcuDescripcion, Set tbAdmSemestrexcursos) {
		this.bnMcuIdn = bnMcuIdn;
		this.vrMcuCodigo = vrMcuCodigo;
		this.vrMcuDescripcion = vrMcuDescripcion;
		this.tbAdmSemestrexcursos = tbAdmSemestrexcursos;
	}

	public long getBnMcuIdn() {
		return this.bnMcuIdn;
	}

	public void setBnMcuIdn(long bnMcuIdn) {
		this.bnMcuIdn = bnMcuIdn;
	}

	public String getVrMcuCodigo() {
		return this.vrMcuCodigo;
	}

	public void setVrMcuCodigo(String vrMcuCodigo) {
		this.vrMcuCodigo = vrMcuCodigo;
	}

	public String getVrMcuDescripcion() {
		return this.vrMcuDescripcion;
	}

	public void setVrMcuDescripcion(String vrMcuDescripcion) {
		this.vrMcuDescripcion = vrMcuDescripcion;
	}

	public Set getTbAdmSemestrexcursos() {
		return this.tbAdmSemestrexcursos;
	}

	public void setTbAdmSemestrexcursos(Set tbAdmSemestrexcursos) {
		this.tbAdmSemestrexcursos = tbAdmSemestrexcursos;
	}

}
