package com.proint1.udea.administracion;

// default package
// Generated 24/11/2014 10:29:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmEstadoSemestre generated by hbm2java
 */
public class TbAdmEstadoSemestre implements java.io.Serializable {

	private String vrEsmCodigo;
	private String vrEsmDescripcion;
	private Set tbAdmSemestres = new HashSet(0);

	public TbAdmEstadoSemestre() {
	}

	public TbAdmEstadoSemestre(String vrEsmCodigo, String vrEsmDescripcion) {
		this.vrEsmCodigo = vrEsmCodigo;
		this.vrEsmDescripcion = vrEsmDescripcion;
	}

	public TbAdmEstadoSemestre(String vrEsmCodigo, String vrEsmDescripcion,
			Set tbAdmSemestres) {
		this.vrEsmCodigo = vrEsmCodigo;
		this.vrEsmDescripcion = vrEsmDescripcion;
		this.tbAdmSemestres = tbAdmSemestres;
	}

	public String getVrEsmCodigo() {
		return this.vrEsmCodigo;
	}

	public void setVrEsmCodigo(String vrEsmCodigo) {
		this.vrEsmCodigo = vrEsmCodigo;
	}

	public String getVrEsmDescripcion() {
		return this.vrEsmDescripcion;
	}

	public void setVrEsmDescripcion(String vrEsmDescripcion) {
		this.vrEsmDescripcion = vrEsmDescripcion;
	}

	public Set getTbAdmSemestres() {
		return this.tbAdmSemestres;
	}

	public void setTbAdmSemestres(Set tbAdmSemestres) {
		this.tbAdmSemestres = tbAdmSemestres;
	}

}
