package com.proint1.udea.produccion;

import com.proint1.udea.administracion.TbAdmPersona;

// default package
// Generated 24/11/2014 10:29:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbPrdMiembrosxgrupo generated by hbm2java
 */
public class TbPrdMiembrosxgrupo implements java.io.Serializable {

	private long nbMieIdn;
	private TbPrdGrupoinvestigacion tbPrdGrupoinvestigacion;
	private TbAdmPersona tbAdmPersona;

	public TbPrdMiembrosxgrupo() {
	}

	public TbPrdMiembrosxgrupo(long nbMieIdn,
			TbPrdGrupoinvestigacion tbPrdGrupoinvestigacion,
			TbAdmPersona tbAdmPersona) {
		this.nbMieIdn = nbMieIdn;
		this.tbPrdGrupoinvestigacion = tbPrdGrupoinvestigacion;
		this.tbAdmPersona = tbAdmPersona;
	}

	public long getNbMieIdn() {
		return this.nbMieIdn;
	}

	public void setNbMieIdn(long nbMieIdn) {
		this.nbMieIdn = nbMieIdn;
	}

	public TbPrdGrupoinvestigacion getTbPrdGrupoinvestigacion() {
		return this.tbPrdGrupoinvestigacion;
	}

	public void setTbPrdGrupoinvestigacion(
			TbPrdGrupoinvestigacion tbPrdGrupoinvestigacion) {
		this.tbPrdGrupoinvestigacion = tbPrdGrupoinvestigacion;
	}

	public TbAdmPersona getTbAdmPersona() {
		return this.tbAdmPersona;
	}

	public void setTbAdmPersona(TbAdmPersona tbAdmPersona) {
		this.tbAdmPersona = tbAdmPersona;
	}

}
