package com.proint1.udea.produccion;

// default package
// Generated 24/11/2014 10:29:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbPrdAutoresxproduccion generated by hbm2java
 */
public class TbPrdAutoresxproduccion implements java.io.Serializable {

	private long nbAppIdn;
	private TbPrdAutor tbPrdAutor;
	private TbPrdProduccion tbPrdProduccion;

	public TbPrdAutoresxproduccion() {
	}

	public TbPrdAutoresxproduccion(long nbAppIdn, TbPrdAutor tbPrdAutor,
			TbPrdProduccion tbPrdProduccion) {
		this.nbAppIdn = nbAppIdn;
		this.tbPrdAutor = tbPrdAutor;
		this.tbPrdProduccion = tbPrdProduccion;
	}

	public long getNbAppIdn() {
		return this.nbAppIdn;
	}

	public void setNbAppIdn(long nbAppIdn) {
		this.nbAppIdn = nbAppIdn;
	}

	public TbPrdAutor getTbPrdAutor() {
		return this.tbPrdAutor;
	}

	public void setTbPrdAutor(TbPrdAutor tbPrdAutor) {
		this.tbPrdAutor = tbPrdAutor;
	}

	public TbPrdProduccion getTbPrdProduccion() {
		return this.tbPrdProduccion;
	}

	public void setTbPrdProduccion(TbPrdProduccion tbPrdProduccion) {
		this.tbPrdProduccion = tbPrdProduccion;
	}

}
